Repository onOffice-Web-Org/oo-wp-plugin, pull requests merged in 2021-08, with the labels that each got.

#47 Contact form interest lead to mail with xml
  plugin/Field/SearchcriteriaFields.php
  plugin/FormPostInterest.php
  tests/TestClassFormPostInterest.php
Labels: enhancement

#68 #11122 configuration of pagination
  plugin/Gui/AdminPageModules.php
  plugin/Installer/Installer.php
  templates.dist/estate/default.php
  templates.dist/estate/default_detail.php
  templates.dist/estate/default_units.php
  templates.dist/estate/similar_estates.php
  tests/TestClassContentFilterShortCodeAddress.php
  tests/TestClassInstaller.php
  tests/TestClassSearchParameters.php
  tests/resources/templates/output_default_detail.html
Labels: enhancement, waiting

#79 11300-radius-not-work-similar-estate
  plugin/EstateDetail.php
  plugin/EstateList.php
Labels: bug

#17 Remove IDE data from repository
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/deployment.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/php.xml
  .idea/vcs.xml
  .idea/wp-plugin.iml
Labels: waiting
