Repository onOffice-Web-Org/oo-wp-plugin, pull requests merged in 2023-08, with the labels that each got.

#522 34477 The Honeypot JS is always being loaded
  js/onoffice-honeypot.js
  plugin.php
  plugin/Form.php
  plugin/ScriptLoader/ScriptLoaderGenericConfigurationDefault.php
  tests/TestClassForm.php
  tests/TestClassFormPostContact.php
  tests/TestClassScriptLoaderGenericConfigurationDefault.php
Labels: in review

#570 34563 Map in property listing
  plugin/DataView/DataListView.php
  plugin/DataView/DataListViewFactory.php
  plugin/EstateList.php
  plugin/Gui/AdminPageEstateListSettings.php
  plugin/Installer/DatabaseChanges.php
  plugin/Model/FormModelBuilder/FormModelBuilderDBEstateListSettings.php
  plugin/Model/InputModel/InputModelDBFactory.php
  plugin/Model/InputModel/InputModelDBFactoryConfigEstate.php
  tests/TestClassDataListViewFactory.php
  tests/TestClassDatabaseChanges.php
  tests/TestClassEstateList.php
  tests/TestClassFormModelBuilderDBEstateListSettings.php
Labels: needs documentation, in review, feature, needs translation

#531 34982 Edit list view
  plugin/Gui/AdminPageEstateDetail.php
  plugin/Gui/AdminPageEstateListSettings.php
  plugin/Gui/AdminPageEstateUnitSettings.php
  plugin/Gui/AdminPageFormSettingsBase.php
  plugin/Gui/AdminPageSimilarEstates.php
Labels: in review

#532 34981 Saving lists or forms without a name
  plugin/Gui/AdminPageAddressListSettings.php
  plugin/Gui/AdminPageEstateListSettingsBase.php
  plugin/Gui/AdminPageFormSettingsBase.php
  plugin/Gui/AdminPageFormSettingsInquiry.php
  plugin/Gui/AdminPageSettingsBase.php
Labels: ready for release, needs translation

#551 35070 Ownerform - GDPR Checkbox
  plugin/FormPostInterest.php
  plugin/FormPostOwner.php
  tests/TestClassFormPostInterest.php
  tests/TestClassFormPostOwner.php
Labels: ready for release, in review

#572 35110 "Geo range search" - the coordinates in the property tiles can not be hidden
  plugin/ViewFieldModifier/EstateViewFieldModifierTypeEstateGeoBase.php
  tests/TestClassEstateViewFieldModifierTypeDefault.php
  tests/TestClassEstateViewFieldModifierTypeEstateGeoBase.php
Labels: ready for release

#571 32987 Similar estates only allow title picture
  plugin/DataView/DataSimilarEstatesSettingsHandler.php
  plugin/DataView/DataSimilarView.php
  plugin/DataView/DataViewSimilarEstates.php
  plugin/Gui/AdminPageSimilarEstates.php
  plugin/Installer/DatabaseChanges.php
  plugin/Model/FormModelBuilder/FormModelBuilderSimilarEstateSettings.php
  plugin/Model/InputModel/InputModelOptionFactorySimilarView.php
  tests/TestClassDataViewSimilarEstates.php
  tests/TestClassDatabaseChanges.php
  tests/TestClassFormModelBuilderSimilarEstateSettings.php
Labels: needs documentation, in review, needs translation

#592 36781 onoffice-style.css with child theme
  plugin/ScriptLoader/ScriptLoaderGenericConfigurationDefault.php
  plugin/Template/TemplateCall.php
  tests/TestClassScriptLoaderGenericConfigurationDefault.php
Labels: in review

#586 36779 Sort property lists
  plugin/Gui/Table/EstateListTable.php
  plugin/Record/RecordManagerReadListViewEstate.php
  tests/TestClassRecordManagerReadListViewEstate.php
Labels: needs documentation, in review, feature
