Repository onOffice-Web-Org/oo-wp-plugin, pull requests merged in 2024-04, with the labels that each got.

#665 41620 Implement City-Select into WP-Plugin
  css/onoffice-multiselect.css
  dist/admin.min.js
  dist/checkbox.min.js
  js/admin.js
  js/checkbox.js
  plugin/DataView/DataListView.php
  plugin/DataView/DataListViewFactory.php
  plugin/EstateList.php
  plugin/Field/Collection/FieldLoaderEstateCityValues.php
  plugin/Field/Collection/FieldsCollectionBuilderShort.php
  plugin/Filter/DefaultFilterBuilderListView.php
  plugin/Filter/FilterBuilderInputVariables.php
  plugin/Gui/AdminPageEstateListSettings.php
  plugin/Installer/DatabaseChanges.php
  plugin/Model/FormModelBuilder/FormModelBuilderDBEstateListSettings.php
  plugin/Model/InputModel/InputModelDBFactoryConfigEstate.php
  plugin/Model/InputModel/InputModelDBFactoryFilterableFields.php
  plugin/Record/RecordManagerDuplicateListViewEstate.php
  plugin/Record/RecordManagerReadListViewEstate.php
  plugin/Renderer/InputFieldComplexSortableDetailListContentDefault.php
  templates.dist/fields.php
  tests/TestClassDataListView.php
  tests/TestClassDataListViewFactory.php
  tests/TestClassDatabaseChanges.php
  tests/TestClassFieldLoaderEstateCityValues.php
  tests/TestClassFormModelBuilderDBEstateListSettings.php
  tests/TestClassRecordManagerDuplicateListViewEstate.php
Labels: QA, feature, component: property list

#660 41593 Screen options in property list overview and form overview
  plugin/Gui/Table/AddressListTable.php
  plugin/Gui/Table/EstateListTable.php
  plugin/Gui/Table/EstateUnitsTable.php
  plugin/Gui/Table/FormsTable.php
Labels: bug, QA, UI/UX, component: property list

#771 45733 onOffice menu item disappears in the WP backend
  plugin.php
Labels: bug, QA, component: dashboard

#680 42302 Can't remove/delete secrets and keys
  css/admin.css
  dist/onoffice-handle-notification-actions.min.js
  dist/onoffice-handle-visibility-google-recaptcha-keys.min.js
  js/onoffice-handle-notification-actions.js
  js/onoffice-handle-visibility-google-recaptcha-keys.js
  plugin.php
  plugin/Controller/AdminViewController.php
  plugin/Gui/AdminPageApiSettings.php
  plugin/Model/InputModelBase.php
  plugin/Renderer/InputFieldGoogleRecaptchaAccountRenderer.php
  plugin/Renderer/InputModelRenderer.php
  tests/TestClassAdminViewController.php
  tests/TestClassInputFieldGoogleRecaptchaAccountRenderer.php
Labels: QA, UI/UX, component: dashboard

#765 45503 implement AreaButler in detail page template
  plugin/DataView/DataViewSimilarEstates.php
  templates.dist/estate/default.php
  templates.dist/estate/default_detail.php
  templates.dist/estate/similar_estates.php
  templates.dist/onoffice-style.css
  tests/TestTemplateEstateDefaultDetail.php
  tests/resources/templates/output_default_detail.html
Labels: QA

#801 Add trigger for labeling
  .github/workflows/development-zip.yml
Labels: deploy test

#803 fix path
  .github/workflows/development-zip.yml
Labels: deploy test

#726 43302 sorting select
  dist/onoffice-sort-list-selector.min.js
  js/onoffice-sort-list-selector.js
  plugin/Controller/SearchParametersModelBuilderEstate.php
  plugin/Controller/SortList/SortListBuilder.php
  plugin/Controller/SortList/SortListDropDownGenerator.php
  plugin/Controller/SortList/SortListTypes.php
  plugin/Renderer/SortListRenderer.php
  tests/TestClassSearchParametersModelBuilderEstate.php
  tests/TestClassSortListBuilder.php
  tests/TestClassSortListDropDownGenerator.php
  tests/TestClassSortListRenderer.php
  tests/TestClassSortListTypes.php
Labels: QA, component: property list, deploy test
