Repository onOffice-Web-Org/oo-wp-plugin, pull requests merged in 2024-06, with the labels that each got.

#831 Fixes for issues with onoffice-unsaved-changed-message.js
  dist/onoffice-unsaved-changes-message.min.js
  js/onoffice-unsaved-changes-message.js
  plugin/Controller/AdminViewController.php
  plugin/Gui/AdminPageApiSettings.php
  plugin/Gui/AdminPageEstate.php
  tests/TestClassAdminViewController.php
Labels: QA, deploy test

#834 43299 Hotfix error multiple select for issues with onoffice-custom-select.js
  dist/onoffice-custom-select.min.js
  js/onoffice-custom-select.js
Labels: bug

#837 49333 Fix critical bug: forms with recaptcha can not be sended and onoffice-captchacontrol.js is also loaded in forms without recaptcha
  dist/onoffice-captchacontrol.min.js
  js/onoffice-captchacontrol.js
  plugin/ScriptLoader/ScriptLoaderGenericConfigurationDefault.php
Labels: bug, deploy test

#710 42678 adaptive image resolution
  css/onoffice-default.css
  plugin/EstateList.php
  templates.dist/estate/default.php
  templates.dist/estate/default_detail.php
  templates.dist/estate/similar_estates.php
  tests/TestClassEstateList.php
  tests/resources/templates/output_default_detail.html
Labels: QA, feature, component: property list, component: property detail page, deploy test

#812 811 redirection error if the url contains parameters
  plugin.php
  plugin/Controller/EstateDetailUrl.php
  plugin/Utility/Redirector.php
  tests/TestClassEstateDetailUrl.php
  tests/TestClassRedirectIfOldUrl.php
Labels: bug
