Repository onOffice-Web-Org/oo-wp-plugin, pull requests merged in 2025-02, with the labels that each got.

#989 Bug/T#4646119-special-char-search
  plugin/Filter/FilterBuilderInputVariables.php
Labels: deploy test

#993 changed styling
  css/admin.css
Labels: deploy test

#992 Fix: do not load region without id
  plugin/Region/RegionController.php
Labels: deploy test

#996 bug/P#128755-special-chars-encoding
  plugin/Controller/InputVariableReaderConfigFieldnames.php
Labels: deploy test

#845 49984 Enhancement of the functionality - total price calculator
  plugin/DataView/DataDetailView.php
  plugin/DataView/DataDetailViewHandler.php
  plugin/EstateCostsChart.php
  plugin/EstateList.php
  plugin/Field/CostsCalculator.php
  plugin/Gui/AdminPageEstateDetail.php
  plugin/Model/FormModelBuilder/FormModelBuilderEstateDetailSettings.php
  plugin/Model/InputModel/InputModelOptionFactoryDetailView.php
  templates.dist/estate/default_detail.php
  templates.dist/onoffice-style.css
  tests/TestClassCostsCalculator.php
  tests/TestClassDataDetailView.php
  tests/TestClassEstateList.php
  tests/TestClassFormModelBuilderEstateDetailSettings.php
  tests/TestTemplateEstateDefaultDetail.php
  tests/resources/ApiResponseGetFieldsCurrency.json
  tests/resources/ApiResponseReadEstatesCostsCalculatorRaw.json
  tests/resources/templates/output_default_detail.html
Labels: QA, feature, component: property detail page, deploy test

#997 Feature/p#127721 extended variable subject line
  dist/onoffice-custom-email-subject.min.js
  js/onoffice-custom-email-subject.js
  plugin/FormPost.php
Labels: deploy test

#943 54016 Improved display of parking options on property pages (multiParkingLot)
  plugin/EstateList.php
  plugin/Field/FieldParkingLot.php
Labels: QA, UI/UX, component: property detail page, deploy test
